Fix CLI backup restore usage message
longhorn/longhorn-engine pull request #539
Opened 2020-09-07 09:01 UTC by c3y1huang

Seems duplicated and safe to remove.

2020-09-08 22:13 UTC, yasker requested changes

2020-09-08 22:13 UTC, yasker commented on app/cmd/replica.go
> +				Usage: "specify backup to be restored, must use with --restore-name",
since there is no subject in the sentence here, it's better to keep `A must be used with B`.

2020-09-09 00:35 UTC, closed without merging

2020-09-09 00:52 UTC, yasker commented
Hmm? @c3y1huang Why is this issue closed? We still need to update the `restore` usage part.

2020-09-09 00:54 UTC, c3y1huang commented
oops, too quick on hand. I will open another.