add nfs server mount directory log (#2242)
longhorn/longhorn-engine pull request #564
Opened 2021-02-25 10:52 UTC by cclhsu

#### Proposed Changes ####

add nfs server mount directory log to resolve ticket '[Question] unable to mount NFS backup' (#2242)

- Add error to log message make directory failed

#### Types of Changes ####

Enhancement

#### Verification ####

#### Linked Issues ####

Refs: https://github.com/longhorn/longhorn/issues/2242

#### Further Comments ####

None

Signed-off-by: Clark Hsu <clark.hsu@suse.com>

2021-03-04 07:02 UTC, shuo-wu approved these changes

2021-03-04 11:55 UTC, joshimoo requested changes
I see no go.mod update to refer to the updated backupstore dependency?
Was that done in a previous pr?

2021-03-04 12:11 UTC, cclhsu commented
> @cclhsu I see no go.mod update to refer to the updated backupstore dependency?
> Was that done in a previous pr?

Thanks! I forget to PR that.  The PR is in https://github.com/longhorn/backupstore/pull/65.

2021-03-04 12:45 UTC, joshimoo commented
@cclhsu merged the backupstore change, you can update the dependency against the new live commit.

Then run 
`go mod tidy`
`go mod vendor`
commit

2021-03-04 14:11 UTC, cclhsu commented
@joshimoo I have updated the dependencies

2021-03-05 09:10 UTC, shuo-wu approved these changes

2021-03-05 09:11 UTC, shuo-wu commented
I don't know what this CI error means
```
default-amd64: 1 error occurred: * <html> <head><title>413 Request Entity Too Large</title></head> <body> <center><h1>413 Request Entity Too Large</h1></center> <hr><center>nginx/1.19.0</center> </body> </html>
```

2021-03-05 17:41 UTC, yasker commented
@shuo-wu I've restarted the drone build. Hopefully it's a hiccup.

2021-03-08 02:43 UTC, shuo-wu approved these changes

2021-03-08 02:53 UTC, innobead approved these changes

2021-03-08 02:54 UTC, merged