Add tcmalloc for amd64 platform
longhorn/longhorn-engine pull request #711
Opened 2022-06-24 04:10 UTC by derekbit

Depends on https://github.com/rancher/tgt/pull/8 and https://github.com/rancher/liblonghorn/pull/16

[Longhorn 4136](https://github.com/longhorn/longhorn/issues/4136)

Signed-off-by: Derek Su <derek.su@suse.com>

2022-07-06 09:32 UTC, innobead submitted a review, later dismissed
LGTM

After discussing, we have two things here.
- Supporting arm64 is probably doable, but right now we only focus on amd64 first (need some testing for arm64
- Just use tcmalloc lib from gperftools installation.

2022-07-06 09:34 UTC, innobead commented
BTW, is this verifiable? Could we understand any obvious performance difference after this introduction? If yes, that will be good.

2022-07-18 05:16 UTC, innobead commented
@derekbit https://github.com/rancher/tgt/pull/8 and https://github.com/rancher/liblonghorn/pull/16 all merged. Do you think this's ready for review?

2022-07-20 07:51 UTC, derekbit commented on package/Dockerfile
> +        zypper -n install autoconf libtool libunwind-devel gcc-c++; \
Addressed. Thank you.

2022-07-20 08:01 UTC, innobead requested changes

2022-07-20 08:01 UTC, innobead commented on package/Dockerfile
> +RUN ldconfig
Suggest moving ldconfig to the end of the previous RUN to avoid an extra layer in the final image.

2022-07-20 08:49 UTC, innobead approved these changes

2022-07-20 09:41 UTC, innobead commented
@derekbit need to backport to 1.3.1. Thanks.

2022-07-20 11:02 UTC, merged