sync: Improve log for the snapshot purge call
longhorn/longhorn-engine pull request #733
Opened 2022-08-05 10:00 UTC by shuo-wu

Longhorn/longhorn#4294

2022-08-05 10:04 UTC, innobead approved these changes

2022-08-05 10:12 UTC, shuo-wu commented
Will update the instance manager vendor after the PR merge

2022-08-08 04:28 UTC, innobead requested changes

2022-08-08 04:28 UTC, innobead commented on pkg/sync/sync.go
> +		return errors.Wrapf(err, "failed to list replicas before purging")
Use `errors.Wrap` instead.

2022-08-08 04:28 UTC, innobead commented on pkg/sync/sync.go
> +				errorMap.Store(rep.Address, errors.Wrapf(err, "failed to get replica client %v during purging", rep.Address))
Suggest "failed to get replica client %v before purging"

2022-08-08 05:57 UTC, innobead commented
@shuo-wu the backport one has been fixed, but this did not. Please help update later, then it's ready to merge.

2022-08-08 07:25 UTC, shuo-wu commented
Oh... I didn't find that `git push` was failed

2022-08-08 07:31 UTC, innobead approved these changes

2022-08-08 08:32 UTC, merged