Tagging netgo to be used while compiling with cgo
longhorn/longhorn-engine pull request #741
Opened 2022-09-06 09:55 UTC by olljanat

~Implements suggestion in https://github.com/longhorn/longhorn/issues/4415#issuecomment-1214885963 and disable CGO here too like it was done in longhorn-manager by https://github.com/longhorn/longhorn-manager/pull/61~

Looks that longhorn-engine needs CGO so switched to alternative solution proposed in https://github.com/longhorn/longhorn/issues/1768#issuecomment-690778513

2022-09-19 07:55 UTC, innobead requested changes
The option is not right, but curious why PR check still passed.

2022-09-19 07:55 UTC, innobead commented on scripts/build
> +go build --tags netgo -ldflags \
```suggestion
go build -tags netgo -ldflags \
```

2022-09-19 13:10 UTC, olljanat commented on scripts/build
> +go build --tags netgo -ldflags \
Good catch. Fixed.

2022-09-26 04:27 UTC, olljanat commented
@innobead typo fixed, please check again.

2022-10-06 11:46 UTC, olljanat commented
ping @shuo-wu @joshimoo @derekbit PTAL, I would like to get those million errors away from logs to be able to better follow if backups works as expected.

2022-10-13 13:59 UTC, innobead commented
@joshimoo Please review this one to see if any uncertain risks.

2022-11-14 02:58 UTC, innobead commented
@longhorn/qa Could you help verify this PR with our e2e test suites to see if all work correctly? @roger-ryao

2022-11-14 03:00 UTC, innobead approved these changes
Merge after QA verification.

2022-11-14 08:02 UTC, roger-ryao commented
Hi @innobead :
    After I built the private image with this PR, Longhorn would be failed to install. 
    
    
![Screenshot_20221114_155648](https://user-images.githubusercontent.com/104337648/201606595-4ef17b20-ffc9-499c-a6a9-470ac40d5541.png)

2022-11-14 10:24 UTC, innobead commented
> Hi @innobead : After I built the private image with this PR, Longhorn would be failed to install.
> 
> ```
> 2022-11-14T09:24:32.302171102Z stderr F cp: cannot stat '/usr/local/bin/longhorn': No such file or directory
> ```
> 
> [longhorn-system_engine-image-ei log](https://github.com/longhorn/longhorn-engine/files/10001522/22.log)
> 
> ```
> Nov 14 09:07:02 ryao-lh1114-w1-3b1b7066-dkwpl k3s[1580]: E1114 09:07:02.201557    1580 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"engine-image-ei-66041e2c\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=engine-image-ei-66041e2c pod=engine-image-ei-66041e2c-2t5dp_longhorn-system(26e78b31-9cfd-4cb2-a237-3c14ace2ecd7)\"" pod="longhorn-system/engine-image-ei-66041e2c-2t5dp" podUID=26e78b31-9cfd-4cb2-a237-3c14ace2ecd7
> Nov 14 09:07:16 ryao-lh1114-w1-3b1b7066-dkwpl k3s[1580]: I1114 09:07:16.200327    1580 scope.go:110] "RemoveContainer" containerID="32cd9be36196da26980a8548ccc9993148b14679d96e3732441ddd2bdd189be6"
> Nov 14 09:07:16 ryao-lh1114-w1-3b1b7066-dkwpl k3s[1580]: E1114 09:07:16.200646    1580 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"engine-image-ei-66041e2c\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=engine-image-ei-66041e2c pod=engine-image-ei-66041e2c-2t5dp_longhorn-system(26e78b31-9cfd-4cb2-a237-3c14ace2ecd7)\"" pod="longhorn-system/engine-image-ei-66041e2c-2t5dp" podUID=26e78b31-9cfd-4cb2-a237-3c14ace2ecd7
> Nov 14 09:07:28 ryao-lh1114-w1-3b1b7066-dkwpl k3s[1580]: I1114 09:07:28.200648    1580 scope.go:110] "RemoveContainer" containerID="32cd9be36196da26980a8548ccc9993148b14679d96e3732441ddd2bdd189be6"
> Nov 14 09:07:28 ryao-lh1114-w1-3b1b7066-dkwpl k3s[1580]: E1114 09:07:28.200951    1580 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"engine-image-ei-66041e2c\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=engine-image-ei-66041e2c pod=engine-image-ei-66041e2c-2t5dp_longhorn-system(26e78b31-9cfd-4cb2-a237-3c14ace2ecd7)\"" pod="longhorn-system/engine-image-ei-66041e2c-2t5dp" podUID=26e78b31-9cfd-4cb2-a237-3c14ace2ecd7
> ```
> 
> [worker_node_1_syslog.log](https://github.com/longhorn/longhorn-engine/files/10001526/syslog.log)
> 
> [describe pod engine-image-ei-66041e2c-5t9gj](https://github.com/longhorn/longhorn-engine/files/10001685/engine-image-ei-66041e2c-5t9gj.log)
> 
> [longhorn-manager.log](https://github.com/longhorn/longhorn-engine/files/10001686/longhorn-manager.log)
> 
> ![Screenshot_20221114_155648](https://user-images.githubusercontent.com/104337648/201606595-4ef17b20-ffc9-499c-a6a9-470ac40d5541.png) cc @longhorn/qa .

As I mentioned, please ensure the customized engine image is right w/ `/usr/local/bin/longhorn`, so if not found, please check how you built the image with other QAs. cc @longhorn/qa

2022-11-15 08:29 UTC, roger-ryao commented
Hi @innobead 
- [core test report](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2456/)
- [regression test report](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2455/)

The test PASS, we could merge `longhorn-engine` PR
cc @longhorn/qa

2022-11-15 08:39 UTC, merged

2022-11-15 08:39 UTC, innobead commented
Thanks @roger-ryao :+1: